### PR TITLE
Bumped to latest version of Trino. Adjusted overrides in OpaAuthorizer

### PR DESCRIPTION
**Pull request by parj**

### CODE REVIEW

**Comment by lfrancke** [comment]
Thank you for the contribution!
Please be aware, that this project is currently in the process of being donated to Trino itself.

I'm only on my phone now and don't have the links at hand. Happy to look at this in detail after the holidays

**Comment by maltesander** [comment]
Hi @parj,

this https://github.com/trinodb/trino/pull/19532 is based on this repo but heavily improved. Once this is merged, Trino has native OPA support :-)

Not sure if it makes sense to go forward in this repo?

Im fine with doing a review and merging this, but then we probably should archive this repo anyways @lfrancke?

Our latest Trino (428) image is already using the upstream OPA changes.

**Comment by lfrancke** [comment]
Make sense to me. Thanks Malte!

**Comment by sbernauer** [comment]
Hi @parj,
many thanks for your contribution, we really appreciate you taking the time to make the proposed changes!

However - as @maltesander hinted previously - we should archive this repository.
The reason is that https://github.com/trinodb/trino/pull/19532 is better and is already at the latest Trino version (as it tries to merge into Trinos master branch).

Additionally, the Trino SPI (mainly the `SystemAccessControl` interface) has many changes since 414 and https://github.com/trinodb/trino/commits/74616968c958b1e35f61ad99a82bca281ed85f5b/core/trino-spi/src/main/java/io/trino/spi/security/SystemAccessControl.java?since=2023-04-19&until=2024-01-17 (e.g. the `checkCanCreateFunction` or the removal of the `checkCanGrantExecuteFunctionPrivilege` function).
We would need address this changes in this PR, as merging this as-is would probably cause issues.

Would you be willing to give https://github.com/trinodb/trino/pull/19532 a try to see if it works for you? One easy way for you to test it, is to use our Trino 428 image, which already contains the new authorizer from https://github.com/trinodb/trino/pull/19532.

**Comment by lfrancke** [comment]
Hi,
just a heads up: if we don't hear back from you by tomorrow we will close this and archive the repository

**Pull request closed without merging**
